### PR TITLE
Collection of Gas Optimisations

### PR DESCRIPTION
**Pull request by Hephyrius**
**Brief:** These changes are to the current master branch code base

**Note:** Further changes may be added over the coming days, some of which are currently in the process of being tested. These changes could also be refactored to squeeze out some extra gas savings, which I will be exploring too.

**Change Log:**

- Removed all Add assembly commands when adding 0, as this is redundant and wasteful. For example: mload(add(Data, 0)) is now mload(Data). Additionally Replaced clear multiplication instances with answer ie such as instances in code such as 32*5 with the answer 160 ~= 250 gas reduction

- Refactored calculation of memory required by lists, using assembly and a new calculate function. This refactor introduces a Function called calculateAndSetupRingLists.  ~= 300 gas reduction

- Refactored ValidateAllInfo using assembly ~= 750 gas reduction

- Refactored checkOrderValid and checkForSubring using assembly. Merging both under a single function called checkValidity~= 950 gas reduction

**Estimated Total Reduction:** ~=2150 gas reduction

**Tests:** All 216 Tests Pass

**Latest Master Branch Gas Report:**

Benchmark gas usage report: 
simpleRingGas:  338677
typicalRingGas: 361322
p2pRingGas:     354619
multiRingGas:   528694
average:        395828

**Optimisation Gas Report:**

Benchmark gas usage report: 
simpleRingGas:  336704
typicalRingGas: 359279
p2pRingGas:     352756
multiRingGas:   525486
average:        393556

- Edit 1: made changes to reflect the new merged checkOrderValidity/checkForSubrings function.

### CODE REVIEW

**Comment by Brechtpd** [comment]
Thanks for this PR. I had a quick look and some of the changes requires quite a lot of assembly for only a minor gas reduction. If the gas usage is only reduced by a small amount we prefer using normal solidity for readability and maintainability so please keep this in mind.

**Comment by Hephyrius** [comment]
What would you say is the minimal gas reduction that would be able to justify assembly usage?

**Comment by Brechtpd** [comment]
That's a difficult question. :) 
It depends on the added complexity. The subring check using assembly and only saving 100 gas is definitely not worth it I think. In general I only do things in assembly when I know normal solidity doesn't produce efficient code, which is mostly data manipulation (from/to bytes for calls/hash calculation). When it's just logic I'd rather have the readability of solidity than the small gas savings that assembly can give for these.

**Comment by Hephyrius** [comment]
Ah yeah this makes a lot of sense thinking about it now. Then again there is always a trade off between human friendly and gas friendly, I guess. 

I was actually testing a change that would have upped the checkForSubring saving to around 300 by refactoring and merging it into checkValidity. I just haven't got around to running the full suite of tests to make sure it doesn't cause issues. In this instance the combined change is around 1000. I'll try and update the commit tomorrow night (GMT/UK time) so you can review this.

I was also working on an alternative schema for the ptrTable/offset that i'm hoping will save a substantial amount of gas. It's still early days on this optimisation, so i'll get back to you with a commit when I actually have it figured!

Last thing, I was wondering what pjs.logconsole (or whatever it is) was supposed to do? I'm guessing its supposed to log data to a file ? If so any indication of where I can find this? I've had to go into the benchmark tests and change these instances to console.log... It'd be nice to copy these values without risking a ctrl-c halt of the tests 😅

**Comment by Brechtpd** [comment]
You can find the logging functions [here](https://github.com/Loopring/protocol2-js/blob/master/src/logs.ts). It's so the logging can be disabled when not needed.  I don't think there's a reason you need to change these. You can run a single test with logging like this (as found in the readme):
`npm run test -- transpiled/test/xxx.js -x`.

**Comment by Hephyrius** [comment]
I added that refactored function I mentioned earlier. I'm also currently working on changes that provide gas reductions with very minor code change, this will be in a separate commit that I will be committing in about an hour or so.

**Comment by Brechtpd** [comment]
Sorry, we have decided not to do any of the changes proposed in this PR. A bit of explanation why:

> Removed all Add assembly commands when adding 0, as this is redundant and wasteful. For example: mload(add(Data, 0)) is now mload(Data). Additionally Replaced clear multiplication instances with answer ie such as instances in code such as 32*5 with the answer 160 ~= 250 gas reduction

Doing this serves two purposes, which of course don't have any impact on the execution, but we still feel are important:
- The code with add(ptr, 0) can be nicely aligned with other code containing add(ptr, X), making it look the same, making it easier to spot errors
- add(ptr, X) is typically used for addressing memory in arrays. By doing the add even with 0 you kind of already get some meaning what is actually happening in the code just by looking at it

> Refactored calculation of memory required by lists, using assembly and a new calculate function. This refactor introduces a Function called calculateAndSetupRingLists. ~= 300 gas reduction

> Refactored checkOrderValid and checkForSubring using assembly. Merging both under a single function called checkValidity~= 250 gas reduction

We'd rather not add complexity here by using assembly for the small gas saving.

> Refactored ValidateAllInfo using assembly ~= 750 gas reduction

The reduction is significant here, but readability really suffers by the use of assembly. Because the function is strictly logical we prefer the code to be as easy to understand as possible.

Thanks again. We really appreciate your contributions!

**Comment by Hephyrius** [comment]
Would you consider the checkOrderValid from my first commit? As despite being 250 less than the combination (Subring and checkOrderValid combination), it still provides a solid 700 reduction. The change in readability of that version is fairly minimal with the comments in place.

**Comment by Brechtpd** [comment]
You're right that currently it could probably be made reasonably readable, but I'd still rather not:
- The assembly code is pretty much a 1:1 translation from the solidity code, nothing is really done that is only possible efficiently in assembly. With some luck the solidity compiler improves in a newer version which makes the solidity version just as efficient.
- The code already gets a bit more complicated with ERC1400 support, and there's a good chance more logic needs to be added in the future. Sticking with a solidity version is the safest option where even someone without assembly knowledge can easily add extra functionality and we don't have to revert back to a solidity version because it gets complicated in assembly.

**Pull request closed without merging**
